version: '2'
services:
  cron:
    image: fballiano/magento2-cron
    depends_on:
      - nginx
      - varnish
    links:
      - cache
      - clusterdata
      - nginx
      - varnish
    volumes:
      - ../magento2/magento:/var/www/html
      - ./varnish.secret:/varnish.secret
      #Enable the next line if you want to add a custom php.ini
      - ./php.ini:/etc/php/7.1/fpm/conf.d/999-customphp.ini

  ssl:
    image: fballiano/nginx-ssl-for-magento2
    depends_on:
      - varnish
    links:
      - varnish
    ports:
      - "443:443"

  varnish:
    image: fballiano/varnish
    ports:
      - "81:80"
      - "6082:6082"
    depends_on:
      - nginx
    links:
      - nginx
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
      - ./varnish:/etc/default/varnish
    environment:
      - CACHE_SIZE=256M

  cache:
    image: fballiano/redis-volatile

  clusterdata:
    image: fballiano/redis-volatile

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - cache
      - clusterdata
    links:
      - cache
      - clusterdata
    volumes:
      - ~/.composer/auth.json:/root/.composer/auth.json
      - ../magento2/magento:/var/www/html
  pwa:
    build:
      context: ./
      dockerfile: ./pwa/Dockerfile
    depends_on:
      - nginx
    links:
      - nginx
    ports:
      - "10000:10000"
    volumes:
      - ../pwa/pwa-studio:/var/www/html
      - ./docker/certs:/etc/nginx/certs